# Generated by Django 2.2.12 on 2022-02-15 15:43

import core.security.audit_mixin.mixin
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de ingreso')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
            bases=(core.security.audit_mixin.mixin.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/%Y/%m/%d', verbose_name='Imagen')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-id'],
            },
            bases=(core.security.audit_mixin.mixin.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_output', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de salida')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
            bases=(core.security.audit_mixin.mixin.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OutputMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Material')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Output')),
            ],
            options={
                'verbose_name': 'Salida material',
                'verbose_name_plural': 'Salida de materiales',
            },
            bases=(core.security.audit_mixin.mixin.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Material')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
            bases=(core.security.audit_mixin.mixin.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EntryMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Entry')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Material')),
            ],
            options={
                'verbose_name': 'Entrada material',
                'verbose_name_plural': 'Entrada de materiales',
            },
            bases=(core.security.audit_mixin.mixin.AuditMixin, models.Model),
        ),
    ]
